jshint/jshint

src/jshint.js, src/state.js, tests/unit/parser.js
In gh-1984, @caitp proposed a quick solution to gh-1983. This is an attempt to resolve the same issue in a more fundamental way. It includes an additional test that demonstrates how this approach addresses a more fundamental issue.
I reused @caitp's commit to preserve the unit test, refactored the parenthesis-balancing logic, and included the fix itself in a separate commit. Here's the message for that last commit:
> Re-use code to parse "fat arrow" function params
>
> Prior to this commit, JSHint parsed "fat arrow" function parameters as though they were expressions in a list. This had unintended side-effects relating to:
>
> 1. the scope of the declared variables. This problem was only partially addressed through manual modification of the data structure for global variables.
> 2. the …
=> Fat arrow args 5

dist/jshint-rhino.js, dist/jshint.js, src/vars.js
Mocha has introduced suiteSetup() and suiteTeardown() but they are undocumented. We should add it.
See also: https://github.com/mochajs/mocha/issues/310
=> Add suiteSetup and suiteTeardown for mocha vars

tests/unit/parser.js
This should hit additional corner cases in lex.js, trivially increasing code coverage in scanNumericLiteral() and scanEscapeSequence(). Please verify that the test case behavior itself is correct since I'm asserting the actual behavior not necessarily the expected behavior for these cases.
=> Add additional test cases to increase code coverage

CONTRIBUTING.md
Document a new commit title tag for commits that modify tests or test infrastructure only. Also, fix a broken link in the contribution guidelines.
=> New commit tag

CONTRIBUTING.md
The JSHint website has some additional details in its version of the
contribution guidelines. Incorporate those details. Additionally,
normalize the Markdown syntax used to designate headlines.
=> [[DOCS]] Update contribution guidelines

CONTRIBUTING.md
Code examples that are associated with bullet points should be indented
so the code is rendered as a child of the list element in the markup.
=> [[DOCS]] Correct Markdown formatting

src/jshint.js, src/messages.js, src/options.js, tests/unit/core.js, tests/unit/options.js, tests/unit/parser.js
A quick attempt at making it possible to ignore this error, while still enabling it by default.
WDYT? I feel like using this feature is typically an error, unless people specifically ask for it, such as for
engine unit tests or polyfill unit tests.
BREAKING CHANGE:
In projects which do not enable ES3 mode, it is now an error by default to use elision array elements,
also known as empty array elements (such as `[1, , 3, , 5]`)
Fixes gh-2062
=> Add option `elision` to prevent warning about empty array elements

src/jshint.js, tests/unit/fixtures/nestedFunctions-locations.js, tests/unit/fixtures/nestedFunctions.js, tests/unit/parser.js
I was getting errors about generators in ES6 classes.
This commit fixes that issue. It also adds several lines of positive tests to guard against regression, including several suggested by rwaldron.
For reference, generators in classes are in the latest ES6 draft spec and work well with 6to5.
NB: I'm resubmitting this PR as Coveralls on Travis kept looking for a nonexistent commit. Original PR was [#2059](https://github.com/jshint/jshint/pull/2059)
=> Support generators in class body

src/jshint.js
Latest coverage report on `master` (demonstrating deadness): https://coveralls.io/files/414078989#L1548
>    The `_.has` utility method checks for the existence of the provided
>    properties as "own" values of the given object. The removed code
>    erroneously uses it to check attributes of an Array. The first branch is
>    (incorrectly) token when statements begin with identifiers/literals "0",
>    "1", or "length", and the nested branch depends on the block type which
>    is never a destructuring assignment in this case.
>    
>    This code has been unreachable since its original introduction into the
>    codebase [1]. Removing it has no effect on the behavior of JSHint.
>    
>    [1] commit fbf34a5
>        Author: Guyzmo <guyzmo+github@m0g.net>
>        Date: …
=> Remove dead code

src/jshint.js
Relevant coverage reports:
- https://coveralls.io/files/423822073#L2488
- https://coveralls.io/files/423822073#L2513
> The removed code was made superfluous by a recent commit that unified
> logic for function parameter parsing [1]. Since then, it has been
> unreachable so it is safe to remove.
> 
> [1] Title: Re-use code to parse "fat arrow" function params
>     Commit: 7430ee539ca2fe1a443b71908b5c36d1689581f5
=> [[FIX]] Remove dead code for parameter parsing

src/jshint.js, tests/unit/core.js, tests/unit/fixtures/es6-import-export.js, tests/unit/parser.js
This adds scoping rules for ES6 modules, ensuring that undef and unused rules accurate reflect
the behavior of ES6 modules on the scope.
This also adds syntax parsing support for `export { foo as bar }` aliasing.
Fixes: #2147
Fixes: #2148
=> [[FIX]] ES6 modules respect undef and unused

src/options.js
These options have long been considered deprecated by JSHint
maintainers. The intention to remove should be communicated in the
source code itself to give advance notice to end users.
=> [[DOCS]] Document deprecated options

src/jshint.js, tests/unit/options.js
This should resolve gh-2067.
> Warnings emitted due to the `singleGroups` option should be in terms of
> the opening parenthesis token of the offending grouping operator.
=> [[FIX]] Correct token reported by `singleGroups`

src/jshint.js, tests/unit/options.js
Parsing logic can generally infer if the current token begins an
expression by referencing the `left` property of the previous token. The
`singleGroups` option relies on this behavior in order to recognize
situations where operator binding power makes the grouping operator
necessary.
Parsing of the "addition" operator should be made consistent with the
other infix operators: the token's `left` property should be set *prior
to* parsing the right-hand-side expression.
This should resolve gh-2139
=> [[FIX]] Correct behavior of `singleGroups`

src/jshint.js, tests/unit/options.js
This adds the bitwise assignment operators to the bitwise unit test, ensuring they trigger warnings when the bitwise option is used.
This also improves test coverage, as no other test was exercising the lexer for some of these assignment ops.
=> [[TEST]] Test all bitwise operators

src/lex.js, tests/unit/parser.js
Previously uncovered territory, improves test coverage metrics.
Test results for bad unicode in a string previously churns out tons of warnings that are hard to follow, so added a more clear warning in that case.
=> [[TEST]] Add tests for bad unicode

tests/unit/parser.js
Include test to ensure lexer/parser can handle escaped character ranges `\[\]`. Improves test coverage of lexer.
=> [[TEST]] Test escaped regex char ranges

src/jshint.js, src/messages.js, src/options.js, src/vars.js, tests/regression/thirdparty.js, tests/unit/options.js
A recent change to JSHint included the ECMAScript 6 global identifiers
in JSHint's collection of "predefined" variables. This disallowed the
definition of those global values even in contexts that did not
implement them.
The intent of this change was to help users avoid bugs when migrating to
the new version of the language. Re-using an existing warning mechanism
caused confusion among many users [1][2][3] for two reasons:
1. The generated warning messages were somewhat misleading (i.e. the
warning "Redefinition of 'Promise'." is inaccurate in ES5
environments)
2. The method of disabling the warnings did not accurately communicate
the intent of the developer (i.e. setting `predef: -Promise` does not
prompt the user to consider the user to consider if creating their
own global variable …
=> [[FEAT]] Implement new option `futurehostile`

CONTRIBUTING.md
The project now uses the CLAHub service to assist in the process of
verifying contributor agreements.
Here's the status report as displayed by GitHub on an unrelated pull request. In the second half of the image, you can see that CLAHub automatically re-checked the pull request after I signed the agreement:
=> [[DOCS]] Update link to CLA

src/jshint.js, tests/unit/parser.js
Rather than add yet another optional positional argument to `doFunction`, I bit the bullet and refactored the function to accept a single "options" argument. This is something we've discussed in the past, so I don't think it's too controversial.
I was hoping to find some way to unify the `name` option and the (proposed) `classExprBinding` option since they both create an entry in the function's scope. These attempts resulted in a strange, error prone API that split apart the function's name (as [given to `functor`](https://github.com/jshint/jshint/blob/4e59553f7e2e09ba6c15643fdcb5b4416301148f/src/jshint.js#L2902) and [used in result reporting](https://github.com/jshint/jshint/pull/1971)) from the variable inserted into the function scope. If there's a better way to combine these …
=> Class expr identifier

src/jshint.js
The parsing logic for the `(` prefix token returns early if the token is
determined to mark the beginning of an arrow function parameter list.
Logic that follows can safely assume that the token is *not* part of an
arrow function parameter lists, and explicit conditions to verify this
are unnecessary.
=> [[FIX]] Remove tautological condition

src/jshint.js, tests/unit/parser.js
This should resolve gh-2168
> In valid JavaScript code, when the `delete` token is parsed as a prefix,
> it will be followed by an expression of some kind. Invalid code may
> include any sequence of characters after the `delete` token, and JSHint
> should be capable of gracefully warning about the syntax error.
>
> Avoid crashing in cases where the `delete` appears as a "prefix" token
> but is not followed by an expression.
=> [[FIX]] Do not crash on improper use of `delete`

src/jshint.js, tests/unit/core.js, tests/unit/fixtures/gh-738-browser.js, tests/unit/fixtures/gh-738-node.js, tests/unit/fixtures/gh-738.js
Makes it possible to use "eval" as a key in an object. Previously this
would have emitted a "W061" warning. "eval" used as the key for a
presumed global ("window" in "browser:true" and "global" in
"node:true") will still emit the warning.
Fixes https://github.com/jshint/jshint/issues/738
Adds unit tests for permitting using "eval" as object key
=> [[FIX]] Permit "eval" as object key

src/jshint.js, tests/unit/fixtures/ignore-w117.js, tests/unit/options.js
This patch allows JSHint to apply `-W117` and `undef:false` to a local part within the file.
Use-case: I have code where some variables are only defined if some conditional is true. I don't want to put `/* globals name_of_variable */` in the file, because it could result in unknowingly using the variable when it does not exist. Therefore I need an option to toggle the error for a specific section.
(edit: `unused` -> `undef`)
=> [[Fix]] Allow W117 and undef to be toggled per line.

src/jshint.js, tests/unit/core.js, tests/unit/fixtures/class-declaration.js, tests/unit/fixtures/function-declaration.js
cc @jugglinmike @caitp 
- `class default function Identifier() {}`
- `class default class Identifier() {}`
- `class default class Identifier extends Heritage() {}`
In all cases, there is a lexical binding, `Identifier`, created.
=> [[Fix]] export default * are defined in lexical module scope. Fixes gh-2197

src/jshint.js, tests/unit/core.js, tests/unit/fixtures/gh-2194.js
src/jshint.js was reading an array at the beginning of a file as JSON instead
of a code block. The parser read the '(begin)' token and then looped 15 times
looking for an end to the block, didn't find it, and considered itself to be
parsing JSON. JSON must use *only* double quotes to be valid, so single quotes
caused warnings.
[JSON spec](http://www.ietf.org/rfc/rfc4627.txt)
=> [[FIX]] Prevent beginning array from being confused for JSON

src/jshint.js, src/options.js, tests/unit/options.js
When enabled, this option generates a new warning for code that would
otherwise pass. Therefore, it should not be enabled by default until the
next major release of this library.
=> [[FIX]] Disable `futurehostile` option by default

src/jshint.js, tests/unit/parser.js
Commit d75ef694385ba44ab49b2d2b2cf1f4bed0949ca7 oversimplified the
information passed to the `doFunction` method.
Prior to that commit, `doFunction` was invoked inconsistently (with a
token and with an object literal). This was incorrectly simplified to a
boolean value, which caused the helper function `isMethod` to stop
working:
function isMethod() {
return funct["(statement)"] && funct["(statement)"].type === "class" ||
funct["(context)"] && funct["(context)"]["(verb)"] === "class";
}
Re-implement the option to be a token and specify consistently at each
invocation of `doFunction`.
=> Allow `this` in class expression methods

src/jshint.js, src/messages.js, tests/unit/parser.js
=> [[FIX]] parse trailing comma in ObjectBindingPattern

src/jshint.js, tests/unit/parser.js
There is a problem when parsing an identifier that would resolve to a
predefined read-only global through the function scope chain.
When checking the block scope for the same identifier only the innermost
block is considered, so while this works:
/* global foo: false */
function x() {
let foo;
foo = {};
}
... a W020 read only warning is generated when moving the assignment
into a subscope:
/* global foo: false */
function x() {
let foo;
{
foo = {};
}
}
By checking the entire block scope chain for the identifier the
assignment generates no warning, as is expected.
=> [[FIX]] Make let variables in the closure shadow predefs

src/jshint.js, tests/unit/options.js
It protects against a relatively benign edge case, but it is absolutely incorrect behavior for the parser to fail to enforce `maxparams` when it is set to 0.
Previously setting maxparams:0 would cause the check to short-circuit,
permitting any number of parameters without issuing a warning. This PR
fixes the bug by testing whether maxparams is a number, instead of
whether it is truthy.
=> [[FIX]] Correctly enforce maxparams:0

src/jshint.js, tests/unit/options.js
As of gh-2242, JSHint unconditionally accepts expressions that compare `typeof` results to the string "symbol". These expressions are only valid in ES6, so they should continue to trigger W122 warnings ("Invalid typeof value") in pre-ES6 code.
I've taken this as an opportunity to extend the internal `isTypoTypeof` function tto accept the `options` object as a formal parameter. This more functional approach avoids  relying on the `state` object through a closure, so the code becomes easier to read and easier to move. This is not strictly necessary for this patch, but it seemed like an appropriate improvement to make while making the change.
> The ES6 specification extended the `typeof` operator to return the
> string "symbol" when when applied to Symbol instances. In …
=> [[Fix]] Only accept "symbol" as a type in ES6 envs

examples/.jshintrc, src/options.js
Options regarding PhantomJS was placed in the Relaxed section
(it should be placed in the environments section).
Also there was no sample options: typed, phantom in example config.
=> [[DOC]] Added more consistency among options file and config example

src/lex.js, tests/unit/fixtures/strings.js, tests/unit/options.js
Previously, the end-of-line loop was immediately followed by the non-quote character code. This
meant that the first character after an EOL was always treated as a non-quote character.
Control flow now returns to the quote character check in the while loop condition immediately
after each EOL or character has been handled, so that this check also runs for the first character
on a line.
Closes #1532. (The commit includes the test case provided in #1532 by DelvarWorld.)
Closes #1319.
=> [[FIX]] Incorrect 'Unclosed string' when the closing quote is the first character after a newline

src/cli.js
Related to https://github.com/iojs/io.js/pull/1153.
They added type checking for ~~`path.dirname`~~ the `path` library and this line below fails
````js
return path.join(path.dirname(file), line.trim());
````
=> [[FIX]] default to empty string in src/cli.js loadIgnores

src/jshint.js, tests/unit/options.js
This addresses two separate issues in everyone's favorite option, `singleGroups`.
The first commit resolves gh-2260
The second commit resolves an as-yet unreported bug regarding the option's behavior with relation operators.
=> Fix singleGroups bugs

src/jshint.js, tests/unit/parser.js
`get` and `set` are both valid identifiers, so they may appear as PropertyDefinitions within a PropertyDefintionList.
(I moved some code around, so adding `?w=1` to the review URL will suppress white space changes and should make reviewing easier.)
Resolves gh-2288.
=> [[FIX]] Accept `get` and `set` as ID properties

package.json
Ideally, I'd like to add tests for this, but that is blocked by the open pull request at gh-2128. In the mean time, it's more important to get the latest version working on the home page.
> When the 3.6.0 release of Lodash is included in a script using
> Browserify, the resulting file cannot be executed in a browser web
> worker context. This is how the jshint.com homepage includes JSHint,
> meaning that the website cannot be updated to demonstrate the latest
> release.
>
> The 3.7.0 release of Lodash addresses this problem [1].
>
> Update to Lodash version 3.7.0 so the next release can be published on
> the JSHint homepage.
>
> [1] https://github.com/lodash/lodash/commit/e28e04a99030ef968a2ab1f9b3d9ed7ea01b7797
=> [[Fix]] Update Lodash

src/jshint.js, src/lex.js, src/messages.js, src/options.js, src/state.js, tests/unit/options.js
@rwaldron @caitp I took a few liberties while implementing this. These aren't (*ahem*) "strictly" necessary, but they've always bugged me, and improving them now made the "module" option easier to implement. They seem pretty low-risk to me, but I've thought that before, so I'd appreciate your review of those changes in particular. (And if you don't think they're improvements, don't hesitate to say so.) They're contained in separate commits to help review (and so I can use commit messages to share justification).
I've introduced a new warning to help people avoid using the new option incorrectly. I've tried to make this generic enough for re-use with other ES6 options, and even for use in future versions.
Note that I've declared this under the "environments" collection of options. My first …
=> [[FEAT]] Impement `module` option

src/jshint.js, tests/unit/parser.js
Although the semicolon token may appear in class bodies in valid ES6
code, it serves no purpose. Extend the parser to accept this token, but
emit the same warning used for unnecessary semicolons appearing
elsewhere. This warning may be disabled by the end user if desired.
=> [[FIX]] Parse semicolons in class bodies

src/jshint.js, tests/unit/options.js
When the `singleGroups` option is enabled, permit two additional usages of the grouping operator. The former (related to immediately-invoked function expressions) is not technically necessary, but is a common pattern used to promote code legibility. The latter (related to arrow functions) is technically necessary.
Resolves gh-2257
=> Relax singleGroups restrictions

src/options.js
In docs (http://jshint.com/docs/options/)
`strict` should be enforcing option,
`globalstrict` should be relaxing option.
=> Options: toggle strict and globalstrict

src/jshint.js, src/lex.js, tests/unit/core.js, tests/unit/options.js, tests/unit/parser.js
I'm not so gung-ho about modifying assertions, but I believe it's an acceptable change. Note that all test cases still pass (JSHint is still failing when it is expected to), but the "shape" of the reported errors is a little different. I would argue the new set of errors are more accurate in some cases, but that's pretty subjective. (See also [this conversation](https://github.com/jshint/jshint/pull/1989#issuecomment-63559108) for the general problem of hard-coding expected errors for invalid source code.) Resolves gh-2324
> Currently, JSHint's lexer continuously emits new "end-of-file" token
> once all input has been consumed. This behavior makes the internal
> `advance` function dangerous to use within iteration contexts. Such
> usages need to explicitly check for the …
=> [[FIX]] Allow lexer to communicate completion

src/vars.js
Mocha exposes the global name `mocha` too for configuration etc. This adds that to the `mocha` environment.
=> Add `mocha` to `mocha` environment

.travis.yml
The Coveralls service occasionally fails to respond within the
continuous integration service's timeout interval. When invoked as part
of the test script, these timeouts trigger build failures.
Move coverage reporting to a task that occurs after build completion[1] so
that these timeouts do not effect build status.
This change also ensures that the project's full set of tests are run in
the continuous integration environment. Previously, only those tests
necessary for generating a code coverage report were executed (omitting
code style and linting checks).
[1] From the TravisCI service's documentation:
> The outcome of any of these commands (except `after_success`,
> `after_failure` or `after_script`) indicates whether or not this build
> has failed or passed. …
=> [[CHORE]] Allow failures in coverage report

src/jshint.js, tests/unit/parser.js
Previously, when an directive was specified without a value, JSHint
would interpret this as the empty string and apply linting rules
accordingly. The empty string is never a valid value for any directive,
so the generated warnings were not appropriate.
If a directive is specified without a value, trigger an explicit error
describing the invalid configuration.
Resolves gh-2261
=> [[FIX]] Do not accept empty values for directives

src/jshint.js, src/state.js
The current `funct` object stores stateful information, so it should be
defined as a property of the global variable reserved for that purpose.
This allows other code to more simply operate based on the current
state because it requires one less reference to be managed across
contexts.
=> [[FIX]] Declare `func` as a property of `state`

.mailmap
Some contributors have authored commits using different e-mail
addresses. Add a `.mailmap` file to allow git to correlate the identity
of these contributors across e-mail addresses.
=> [[DOCS]] Introduce a mail mapping file

src/options.js
ES6 is already finalized on June 17.
Ref: http://www.ecma-international.org/news/Publication%20of%20ECMA-262%206th%20edition.htm
=> [[DOCS]] Update notation about `esnext` option

src/jshint.js, tests/unit/options.js, tests/unit/parser.js
@rwaldron You're gonna love this.
Since the first public release of JSLint (ca120a7), this codebase has
automatically enabled the `newcap` option for all strict mode code:
function use_strict() {
if (nexttoken.value === 'use strict') {
advance();
advance(';');
strict_mode = true;
option.newcap = true;
option.undef = true;
return true;
} else {
return false;
}
}
Commit 8de8247 unified the way JSHint detects and enforces strict mode
across contexts. Among other modifications, it included the following
change:
- if (state.tokens.curr.value === "use strict") {
+ if (state.isStrict()) {
if (!state.option["(explicitNewcap)"]) {
state.option.newcap = true;
}
state.option.undef = true;
}
This change introduced a regression: it enables the `newcap` option for
class bodies and ES2015 module code as …
=> [[FIX]] Do not enable `newcap` within strict mode

src/vars.js
Adds support for notOk exposed to the global object since QUnit 1.18.0
Ref https://github.com/jquery/qunit/releases/tag/1.18.0
=> [[FEAT]] Support QUnit's global notOk

src/state.js, tests/unit/options.js
Although environments implementing Mozilla extensions are not
necessarily ES6-compliant, they are not mutually exclusive. Ensure that
for configurations that specify both ES6 and `moz`, the semantics of
both environments are applied consistently.
Resolves gh-2785.
=> [[Fix]] Do not disable ES6 when `moz` is set

src/scope-manager.js, tests/regression/thirdparty.js, tests/unit/fixtures/scope-cross-blocks.js, tests/unit/fixtures/unused-cross-blocks.js, tests/unit/options.js, tests/unit/parser.js
In the absence of the `funcscope` option, JSHint validates
function-scoped variable references as though they were block scoped.
JSHint does not apply block-scoping semantics to reference counting,
however: re-declarations within nested blocks are *not* considered
distinct when determining whether a given binding is used.
Ensure that when a variable is re-declared within the same function
scope, usage tracking is "shared" across all identifiers.
This change required correcting two existing tests. Both alterations
removed warnings, meaning they do not reflect a backwards-incompatible
change in behavior.
1. In the following source code, the variable `ok` is used, so JSHint
should not report otherwise:
function(match) {
var ch = this.string.charAt(this.pos);
if (typeof match == "string") var …
=> [[Fix]] Correct `unused` for function-scoped vars

src/jshint.js, tests/unit/options.js, tests/unit/parser.js
> When an invalid set of configuration values is encountered, linting cannot
> continue because the expectations are ambiguous. In this event, report the
> error and cease linting.
Note that the current behavior of JSHint is to issue an error and continue linting. As @nicolo-ribaudo pointed out in gh-2760, a distinct "invalid configuration" error is reported for every inline directive encountered thereafter. In addition, because the program is in an invalid state, it's difficult to say how it will apply linting rules in general. That's why I'm proposing that we halt all linting in this case.
This change is **not** critical. If we want to play it safe while vetting 2.9.1's release candidate, then we can proceed with the existing behavior. The program will fail regardless, so even a patch …
=> [[Fix]] Abort in the presence of invalid config

src/jshint.js, tests/unit/parser.js
A very low priority fix...
(note `0% scanned` instead of `NaN% scanned`)
```
nicol@DESKTOP-EDGLMME MINGW64 ~/Documents/jshint (master)
$ bin/jshint demo.js
demo.js: line 1, col 1, Unrecoverable syntax error. (NaN% scanned).
1 error
nicol@DESKTOP-EDGLMME MINGW64 ~/Documents/jshint (0%-scanned)
$ bin/jshint demo.js
demo.js: line 1, col 1, Unrecoverable syntax error. (0% scanned).
1 error
```
demo.js
```js
}
```
=> [[FIX]] Don't throw '(NaN% scanned)'

src/jshint.js, src/state.js, tests/unit/options.js
While working on gh-2801, @rwaldron and I identified another opportunity to
disallow ambiguous configurations. As of this writing, the `esversion` option
is not yet available in any stable release, which means that we are free to
introduce hard failures in its interpretation. This will not be possible
following the next stable release, and that is why we are considering it during
the release candidate phase.
@rwaldron: This required more refactoring than I expected, but (as I tried to
explain in the commit message) I think it's necessary. During your review,
please pay close attention to the handling of the `moz` option in particular.
As you know, the codebase has always made surprising assumptions about that
option. I believe the simplifications in this patch are all valid, but I would …
=> [[Fix]] Disallow ambiguous configuration values

src/jshint.js, src/options.js, tests/unit/envs.js, tests/unit/options.js
In web browsers, enabling ES5 "strict mode" at a global level effects
all scripts executed in the same context. For this reason, the `strict`
option was originally implemented to enforce the directive's use in
function scope only.  However: the Browserify, Node.js, and PhantomJS
environments do not suffer from this problem.
Recent improvements to the option's behavior included making JSHint's
interpretation of `strict: true` to be contextual: in those environments
where a global `use strict` directive is "safe," enabling the option
would require the global directive.
Although this change is an improvement (because it encourages more code
to be written in strict mode), it is backwards incompatible. Moreover,
the option's documentation in JSHint 2.8.0 explicitly described the
sub-optimal …
=> [[FIX]] Do not require global USD for any envs

src/jshint.js, src/state.js, tests/unit/options.js
In addressing gh-2836, I ran across some inefficient/noisy behavior. Rather
than address that as part of the bug fix, I'm going to follow up with a
separate commit. For now, I'm submitting a separate commit to assert the
undesirable behavior, just to document that it isn't a regression introduced by
my bug fix.
Resolves gh-2836.
=> [[FIX]] Do not fail on valid configurations

src/jshint.js, tests/unit/options.js
This warning is inappropriate in cases where `esversion` has been
globally set to a value other than `5` (e.g. in a project's `.jshintrc`
file) and a specific file overrides this value with an in-line
directive.
Although it is possible to detect this case while interpreting option
values, the warning itself has minimal utility. Some users may set
options to their default values in the interest of explicitness.
Preventing this practice (and doing so inconsistently--only for the
`esversion` option) adds little value.
Remove I003 completely.
=> [[CHORE]] Remove I003

src/jshint.js, src/scope-manager.js, src/state.js, tests/unit/core.js, tests/unit/envs.js, tests/unit/options.js
@rwaldron I'm not a fan of this patch. But it does what it needs to do.
I started with an approach that I think is superior, but I eventually
discovered that it is incompatible with the legacy behavior of "environmental"
options:
https://github.com/jshint/jshint/compare/master...jugglinmike:implied-closure
I'm sharing that link here because I'm not convinced that the breakage is
meaningful. It might be a small enough edge case that we try it out in an RC.
> Some environments wrap code in an immediately-invoked function
> expression prior to evaluation. This behavior has an effect on global
> `var` declarations. Unlike in typical JavaScript source code, such
statements in these contexts do *not* create new entries in the
> environment record, nor do they resolve to …
=> [[FIX]] Account for implied closures

src/lex.js, tests/unit/module-api.js, tests/unit/parser.js
I found this bug while reviewing gh-2846. The fix there is valid, but it did
not address an underlying problem with the little-known "module" API.
Unfortunately, neither JSHint nor NodeUnit are built to support testing this
behavior effectively. As noted in the first (test-only) commit, I've factored
the only test for the API into its own file and encapsulated necessary
setup/teardown logic there.
The second commit addresses the bug.
As an aside: I'm not convinced that this API is useful (or used!), but it ought
to at least be correct.
=> [[FIX]] Emit correct token value from "module" API

src/jshint.js, tests/unit/options.js
(Little noisier than I would like... Use [`?w=1` to see a simplified changeset for the `isReserved` function](https://github.com/jshint/jshint/pull/2879/files?w=1).)
From the ECMAScript 2015 specification:
> The following tokens are reserved for used as keywords in future
> language extensions.
>
>     Syntax
>         FutureReservedWord::
>             enum
>             await
>
> await is only treated as a FutureReservedWord when Module is the goal
> symbol of the syntactic grammar.
http://www.ecma-international.org/ecma-262/6.0/#sec-future-reserved-words
=> [[FIX]] Reserve `await` keyword in ES6 module code

src/jshint.js, tests/unit/options.js
The extension to `nud` is a fairly low-level change for such a fringe feature
as "singleGroups", but I believe it is technically necessary to expose correct
behavior. It doesn't seem too dirty--the change is functional and does not rely
on additional global state.
And believe it or not, this is actually blocking my patch for gh-2923 (`yield`'s
binding power is a little tricky).
I'm curious to hear what others think! Especially @caitp and @rwaldron :)
---
The grouping operator may be necessary if the right-binding power of the
operator preceeding the "(" token is greater than the left-binding power
of the operator immediately following it.
The initial implementation approximated this behavior by using the
readily-accessible left-binding power of both operators. This heuristic
is not always …
=> [[FIX]] Correct behavior of singleGroups

.travis.yml, tests/cli.js
Note the additional commit here: this required removing a brittle assertion in
the CLI tests.
=> Run CI in "latest" and "LTS" releases of Node.js

src/jshint.js, tests/unit/parser.js
The lexer returns `null` values when tokens are requested after all
input has been consumed. Previously, the `peek` function would correctly
produce the special "(end)" token in situations where the parser
attempted to look beyond the end of the program. In such cases, however,
it would also pollute the lookahead buffer with an invalid entry--the
`null` value returned by the lexer. Future calls to `peek` could receive
this buffered value.
Because JSHint's internals are written with the assumption that `peek`
always returns a token object, the `null` value would trigger a
TypeError and subsequent program crash.
Re-factor the `peek` function to only insert valid token objects into
the lookahead buffer.
=> [[FIX]] Avoid crash when peeking past end of prog

src/jshint.js, tests/unit/options.js
Extend the recently-improved `isEndOfExpr` function so that it may be
re-used during directive parsing, limiting duplication.
---
@nicolo-ribaudo this refactors some of your work from gh-2716 to re-use the
recent general improvement to ASI interpretation from gh-2977. What do you
think?
=> [[CHORE]] Refactor directive parsing logic

src/jshint.js, src/messages.js, tests/unit/options.js, tests/unit/parser.js
At long last, here is a fix for gh-2923! You'll note the very first thing this
patch does is factor out the Mozilla-JavaScript-1.7-specific logic into a
standalone function. I think we 'd all like to remove `moz` one day, but until
then, this seems like the safest/most readable way to change the ECMAScript
standard version. (Since we we have no means to verify conformance with the
Mozilla-specific extension and no bug reports for that implementation, I've
elected to maintain behavior there.)
@rwaldron Would you mind reviewing this for me?
=> Correct parsing of YieldExpression

src/jshint.js, tests/unit/parser.js
When JSHint encounters an "open parenthesis" token, it must determine if
the token marks the beginning of an arrow function or a grouping
operator before parsing can proceed.
To make this determination, it inspects the token stream to find the
corresponding "close parenthesis" character.
Previously, this lookahead behavior halted whenever a semicolon token
was encountered. This was presumably an optimization to allow the
algorithm to exit early in the event of an unmatched "open parenthesis"
token.
Because a semicolon token may appear in the parameter list of an arrow
function (e.g. within a default parameter value that is a function
expression), the presence of such a token does *not* necessarily
indicate that the "open parenthesis" is unmatched.
Remove the condition concerning the …
=> [[FIX]] Support semicolons within arrow fn params

package.json
The `cli` module at this version range was recently found to have a
security vulnerability in a feature that is not used in JSHint. Update
to the latest version which resolves the vulnerability by removing the
affected functionality.
=> [[CHORE]] Update dependency: cli

src/messages.js, tests/unit/options.js, tests/unit/parser.js
W014 was previously implemented with the following message:
> Bad line breaking before '{ token }'.
This message does little to explain the rationale for the warning or the
means to correct it. Re-phrase the message to better reflect the
intention.
=> Rephrase message for W014

src/lex.js, tests/unit/parser.js
Extend the lexer to recognize RegExp literals which immediately follow
the `yield` operator.
=> [[FIX]] Allow RegExp literal as `yield` operand

src/cli.js, tests/cli.js
Without this fix JSHint fails if the three conditions are true: 
1. it's run on Windows,
2. the current path contains characters like `++`,
3. ignore patterns are specified via .jshintignore or command line.
=> Fix the check if a file is ignored

src/jshint.js, tests/unit/parser.js
A recent extension to the `instanceof` operator introduced logic that
performed property access on the result of parsing the operator's
right-hand expression operand. Because invalid code may not specify such
an expression, this logic led to program crashes in response to the
invalid syntax.
Ensure that when the `instanceof` operator appears without a right-hand
expression operand, JSHint reports a syntax error and exits gracefully.
This should resolve gh-3039. @rwaldron mind taking a look?
=> [[FIX]] Avoid crashing on invalid input

src/jshint.js, tests/unit/parser.js
Previously, the following operators were incorrectly interpreted as
"infix" operators:
- `++`
- `--`
- `yield`
The internal `isInfix` function tended to obscure this error because it
identified "infix" tokens via a boolean logic expression that acted as a
blacklist. This expression was difficult to understand and hostile to
future extensions for new language features (because future tokens could
be mistakenly implemented as "infix" operators).
Update all "infix" operator token definitions to explicitly define the
`infix` property, obviating the need for the internal `isInfix`
function. Ensure that the aforementioned tokens are not interpreted as
"infix" operators, This corrects the behavior of the internal
`isEndOfExpr` function, which is appreciable when linting code that
relies on …
=> [[FIX]] Correct interpretation of ASI

src/jshint.js
As noted in the in-line comment, the current behavior is a result of a
programming error. It may not be resolved outside of a major release
because the project documentation does not describe the more desirable
consistent behavior.
---
@rwaldron We may not be able to fix it today, but we can at least same
some cycles (and confusion) by commenting this out.
=> [[DOCS]] Document inconsistent behavior

src/jshint.js, tests/helpers/testhelper.js
When reporting unrecoverable errors, JSHint would insert two elements
into the global `errors` array: a descriptor for the error itself, and a
`null` value. Because this behavior is undocumented and inconsistent, it
is most likely the result of a programming error. Ensure that the
`JSHINT.errors` collection contains only error descriptor.
---
@rwaldron This has been around since the first commit!
https://github.com/jshint/jshint/blob/ca120a731db548c0014320fa0c196edc613536ae/fulljslint.js#L5509
Funny how the testing infrastructure was built up to tolerate it.
=> [[FIX]] Remove `null` value from `errors` array

src/jshint.js, src/scope-manager.js, tests/unit/core.js, tests/unit/options.js
This patch includes work by @nicolo-ribaudo (originally submitted in gh-2701) and a refactoring of my own design.
I initially expected that this approach would reduce some of the noise
associated with explicit maintence of the standalone "definition" objects (e.g.
the calls to `state.funct["(scope)"].definition.reset`). While this turned out
to be true, I found that it *also* introduced a different kind of noise--see
the extra calls to `state.funct["(scope)"].initialize`.
I think the latter is preferable because it makes the source code more closely
match the spec language. Readers are more likely to know what it means to
"initialize a label" than what it means to "clear a definition."
Resolves #2637
=> Enforce TDZ within initializer of lexical declaration (refactored)

src/jshint.js, tests/helpers/testhelper.js, tests/unit/core.js, tests/unit/parser.js
The final commit is where it's at. The first two (along with https://github.com/jshint/jshint/pull/3049 before them) address more minor bugs in service of that change.
=> Do not duplicate reported warnings/errors

src/options.js
As an "enforcing" option, `unused` is not enabled by default. The phrase
"by default" should be avoided because it may be interpreted to describe
JSHint's behavior when the option is not enabled.
This should resolve gh-2358. Wouldn't you agree, @rwaldron?
=> [[DOCS]] Improve description of `unused` option

.travis.yml, src/jshint.js
A previous commit removed all references to an internal function,
introducing a linting error. This was not reported by the project's
continuous integration system because that system was not configured to
run the project's linting check.
Correct the linting error and enable linting in the continuous
integration environment.
=> [[CHORE]] Fix linting error and enable lint in CI

src/jshint.js, tests/unit/core.js
When a function declaration without an identifier is encountered, JSHint
issues a warning and attempts to continue parsing the declaration.
Previously, JSHint created a new binding for the "function" keyword, and
because such a binding can never be referenced, this would generate
spurious warnings when the "unused" option was enabled.
Do not create a faulty binding in the presence of this syntax error.
=> [[FIX]] Do not create binding for illegal syntax

src/scope-manager.js, tests/unit/options.js
The risk of confusion for functions declared within loops only pertains
to references to mutable bindings. Relax the wanting regarding
"confusing semantics" to only occur in the presence of one or more
references to mutable bindings.
=> [[FIX]] Allow closing over immutable bindings

tests/helpers/testhelper.js
Previously, the project's test suite generated error messages which
included formatting directives related to text rendering. These
directives no longer modify the style of the text rendered to the
terminal; instead, they only introduce additional noise in the failure
reports.
- Remove the formatting directives to improve the readability of error
reports
- Expand the logic that generates error messages to improve the
readability of the test suite's source code
- Suppress test title in cases where it is not specified
- Consistently report expected character position
---
This has bugged me for years. For the longest time, I assumed that the noise in
the test suite's error reports was due to a misconfiguration in my system. I
imagine that contributors either made the same assumption or …
=> [[CHORE]] Improve reporting in project test suite

src/jshint.js, src/scope-manager.js, tests/test262/expectations.txt, tests/unit/core.js
Ensure that duplicate parameters in arrow functions are always reported
as a SyntaxError (regardless of strict mode and regardless of whether
the function has a block body.
@rwaldron DI discovered this while updating gh-3177. This one should land first.
=> [[FIX]] Report error for duplicate arrow params

src/jshint.js, src/messages.js, tests/unit/core.js, tests/unit/fixtures/es6-import-export.js
`export` declarations with empty export export clauses are not
necessarily superfluous: if they also specify a "from" clause, they will
cause the referenced module to be evaluated. Because of this, the
warning produced in these cases should be contextual--it should
recommend removal only if no "from" clause is present. In the presence
of such a clause, the warning should instead suggest use of a
binding-free `import` declaration (as this clearly communicates the
intention to evaluate a module without requesting any bindings).
Notes on compatibility:
- The previous warning behavior had not yet been published in a stable
release (it was implemented at the same time as the parser was
corrected to support `export` declarations without bindings). This
makes this change in warning behavior …
=> [[DOCS]] Expand warning message

src/jshint.js, src/lex.js, tests/unit/core.js, tests/unit/parser.js
Removed old "functionicity" variable, that was used only in useless "for" cycles, which did nothing but adding and removing the same properties to the "fu" object over and over again.
Also, noticed several typing errors like "tokens.current" instead of "tokens.curr"; "v.raw_text" instead of "v.token.raw_text" etc.
Also, property "tokens[0].first" is not used anywhere in the code and can be removed.
And the last thing, function classbody doesn't return anything, so there is no point to assign undefined value to the "c.body" property.
=> [[FIX]] Fixing typos and some dead old code

src/vars.js, tests/unit/envs.js
Added `spyOnProperty` (introduced in Jasmine 2.6) to the list of known globals.
Fixes #3183
=> [[FIX]] recognize Jasmine global `spyOnProperty`

package.json, tests/browser.js
@rwaldron In gh-3209 and gh-3210, you reported that JSHint is now failing its
own tests when run with the 0.10 and 0.12 releases of Node.js. You were right
that the error originates from a nested dependency: ironically, an npm module
named `boom`. My initial plan was to work with the maintainers of that module
to revert the change in a patch release and re-apply it in a new major version.
That turned out to be unnecessary because `boom` released a new major version
when it dropped support for legacy versions of Node.js. The real issue is how
that module has been consumed elsewhere.
The module `hawk` (which depends on `boom`) likewise incremented its major
version number in recognition of the breaking change. Unfortunately, the
`request` module (which depends on `hawk`) [did not follow …
=> [[FIX]] Preserve functionality in "legacy" Node.js

src/lex.js, tests/unit/parser.js
Hey @rwaldron. I imagine that a patch like this would cause you to wonder about my priorities. Rest assured: I'm focused on async functions these days. I just stumbled on this corner case while trying to parse `await` correctly.
=> [[FIX]] Tolerate RegExp as `void` operand

src/cli.js, tests/cli.js
When the Node.js CLI is invoked with a path to an input file, that file
should not be linted if it matches any pattern in a "ignore list"
configuration file.
Prior to this patch, JSHint failed to ignore such files if one of their
parent directories was prefixed with a period character.
Update the CLI's usage of the `minimatch` Node.js library to also
consider such "dot-prefixed" directories when interpreting ignore lists.
Note that this change is backwards-compatible because it limits the
situations in which the CLI reports an error.
=> [[FIX]] Consistently ignore dot-prefixed dirs

tests/unit/parser.js
Validate JSHint's behavior for various invalid applications of the
"rest" operator in isolation. In the previous factoring, the independent
syntax tests interacted and caused JSHint to report errors that differ
from those it would report when encountering each form in isolation.
Although JSHint makes a best-effort approach to recovering from invalid
syntax, this behavior is not formalized and should therefor not be
asserted by unit tests.
This factoring avoids the undesirable interaction, allowing the tests to
document JSHint's behavior under more predictable conditions. It also
highlights a previously-existing bug in the errors reported (as
documented via in-line code comments).
---
@rwaldron Mind taking a look? This is pretty minor, but it will help me while rebasing the `v2.10.0` …
=> [[TEST]] Refactor negative syntax tests for "rest"

src/jshint.js, tests/unit/parser.js
Ensure that the special "end" token cancels parsing of the `for`
statement "head" in all cases.
---
Hey @rwaldon. The modified parsing logic has problems that extend beyond the
issue reported in gh-3230. As you know, we've refactored that code heavily in
the feature branch for the next minor release, so the problem is already fixed
there. But since we don't have a solid plan for 2.10.0 yet, I've implemented
this different solution so we can resolve the bug in our next patch release.
This will cause merge conflicts for the 2.10.0 feature branch, but I'm prepared
to resolve those.
=> [[FIX]] Avoid infinite loop on invalid `for` stmt

tests/helpers/testhelper.js
Today, when a test expects an error to occur on a line that is
incorrect, the harness reports the situation in those terms. For
example, for the following test:
exports.foo = function (test) {
TestRun(test)
.addError(9999, 1, "Expected an assignment or function call and instead saw an expression.")
.test("0;");
test.done();
};
The test harness reports:
>     Errors with wrong location:
>       {Line 1, Char 1} Expected an assignment or function call and instead saw an expression. - Not in line(s) {Line 9999, Char 1}
The requirement for tests to specify the character column for every
error is a recent addition to the test harness [1]. It was introduced
with only partial support in the test harness. That flaw did not impact
the harness's ability to identify test failures, but it did produce …
=> [[CHORE]] Correct bug in test harness

src/jshint.js, tests/unit/parser.js
@rwaldron this is another fix in support of gh-2604
=> [[FIX]] Restrict "name" of strict mode functions

src/lex.js
Lex NullLiterals and BooleanLiterals as keywords, not Identifiers. This
simplifies the `scanIdentifier` function and makes its name more
accurately describe its behavior. It also obviates the need for two
token "types" that are internal to the lexer itself (as in either case,
the "type" attribute of the emitted token object is "(identifier)".
=> [[CHORE]] Simplify lexing of literal values

src/jshint.js
Version 3 of the Lodash module contains a security vulnerability. That
vulnerability was patched in the 4.17.5 release.
Note that version 4 of Lodash removes support for Internet Explorer 6,
7, and 8. The JSHint project does not formally document compatibility
with web browsers, but the source is currently dependent on Array
prototype methods introduced in ES5. This means that updating Lodash
does not effect the set of browsers supported by this project.
[1] https://hackerone.com/reports/310443
[2] https://github.com/lodash/lodash/wiki/Changelog#v400
Signed-off-by: Mike Pennisi <mike@mikepennisi.com>
=> [[CHORE]] Update to latest version of Lodash

src/jshint.js, tests/unit/parser.js
The ECMAScript specification details the following early error for
function-defining productions:
> - If the source code matching this production is strict mode code, it
>   is a Syntax Error if BindingIdentifier is present and the
>   StringValue of BindingIdentifier is "eval" or "arguments".
There were two bugs in the original implementation of this error:
- violations from function expressions with empty bodies would not be
detected
- violations from function declarations contained within strict mode
code would be reported twice
Correct the first issue by ensuring that the "(isStrict)" property is
accurately set for functions with empty bodies. Correct the second issue
by re-locating the error detection logic to within the processing logic
for expressions and declarations and inserting …
=> [[FIX]] Correct restriction on function name

.travis.yml, appveyor.yml, package.json, scripts/generate-identifier-data.js, scripts/remove-dev-dependencies.js
We've received a couple reports (gh-3316 and gh-3318) that the installation size of JSHint increased drastically in the recently-released version 2.9.6.  This is easily verified using npm's `--production` flag:
mkdir nodemods
git checkout 2.9.5
npm install --production
mv node_modules nodemods/2.9.5
git checkout -- package.json
git checkout 2.9.6
npm install --production
mv node_modules nodemods/2.9.6
du -h -d 0 nodemods/*
Output:
9.9M    nodemods/2.9.5
277M    nodemods/2.9.6
Two independent commits contributed to this 20-fold increase in side. This patch addresses each of them in turn. You can verify using the same technique:
git checkout shrink-deps~
npm install --production
mv node_modules nodemods/2.9.6-phantom
git checkout -- package.json
git checkout shrink-deps
npm install …
=> Reduce package size

src/jshint.js, tests/unit/core.js
- [[CHORE]] Remove superfluous statement
- [[FIX]] Honor `globals` config in JavaScript API
Prior to this commit, the `globals` configuration value was not
considered for invocations of the JavaScript API. Ensure that option is
consistently interpreted according to the project documentation. Ensure
that globals defined by the more specific `predef` option of the API
take precedence over globals defined using this configuration option.
(Owing to a change in indentation, this changeset is best reviewed with git's `-w` flag.)
This should resolve gh-3321
=> Honor `globals` config in JavaScript API

src/scope-manager.js, tests/unit/parser.js
That this correction does not require a modification to the Test262
expectations file is an indication of missing coverage in that project.
New tests have been submitted there, as well [1].
[1] https://github.com/tc39/test262/pull/2043
=> [[FIX]] Enforce UniqueFormalParameters for methods

src/jshint.js, tests/unit/options.js
A recent refactoring of the class parsing logic [1] removed the function
name inference logic (i.e. integration with the `nameStack` object) in
favor of a similar codepath within the generic `doFunction` routine. By
providing the method name to that routine, the change had an unintended
side effect: method names were used to create new entries in the new
environment record. This was observable from user code in the presence
of JSHint's `unused` linting option: when set, methods would incorrectly
shadow variables that shared the same name.
Continue to rely on the `doFunction` method for name inference (limiting
duplication), but disable the extension of the environment record for
that case.
This is intended to resolve gh-3354.
=> [[FIX]] Do not add cls method names to env. record

src/lex.js, tests/unit/parser.js
Do not interpret RegExp syntax characters using their specialized
semantics when they appear within a character set.
This is intended to resolve gh-3356
=> [[FIX]] Correct parsing of RegExp character sets

src/scope-manager.js, tests/unit/parser.js
Correct typo to promote consistency in enforcement of linting rule.
---
@rwaldron since the typo shipped in version 2.10.0, fixing it is technically a breaking change. However, I think this is pretty unambiguously a bug fix, so waiting for the next major doesn't seem appropriate. What do you think?
=> [[FIX]] Warn on reassignment of async functions

src/jshint.js, tests/unit/core.js, tests/unit/options.js, tests/unit/parser.js
ES5 allowed a number identifiers which were previously classified as
FutureReserve to be used as binding identifiers. Ensure that when input
code defines such identifiers, usage counting operates as expected.
Although this patch is intended to correct a regression introduced by
commit f80e049c, it exposes a previously-existing bug. Prior to this
patch, JSHint did not flag FutureReservedWords when used as
IdentifierReferences. Correct this behavior since deferring a correction
to a dedicated commit would require additional and ultimately useless
logic.
---
@rwaldron JSHint creates dedicated entries in the symbol table for each of
ES3's FutureReservedWords. I'd like to lex them as identifiers and attach a
special property. Or maybe just create on symbol for them all to share. Either
change …
=> [[FIX]] Track FutureReservedWords as idnts in ES5+

src/jshint.js, tests/unit/core.js
The first commit is intended to resolve gh-3370. The second fixes an as-yet unreported bug.
=> Correct parsing of block binding declarations in C-style for loops

src/jshint.js, tests/unit/objrestspread.js
Previously, JSHint interpreted token sequences following the "object
rest" operator as expressions. As noted in the in-line comment, this was
done to improve the chance of recovery in response to a common
programming error. Unfortunately, it also caused valid syntax to be
misinterpreted--the expected identifier was treated as a
IdentifierReference instead of a BindingIdentifier.
Update the parsing strategy to use the expression parsing fallback only
when the input is known to be invalid.
This should resolve gh-3377
=> [[FIX]] Interpret "object rest" ident as a binding

src/jshint.js
The function `checkLeftSideAssign` validates assignment targets and
includes a branch for targets which are applications of the spread/rest
operator. Although the symbol table includes an entry for the `...`
token, its definition as an "infix" operator is incomplete and cannot be
used to advance through an expression (e.g. the invalid code `0 ... 1`).
Instead, the operator is explicitly consumed in the productions where it
is allowed through the use of the internal `spreadrest` function. This
means the token is not used to build an expression. Therefore, the
branch in `checkLeftSideAssign` accommodates a condition that cannot
occur, and it may be removed without altering the behavior of JSHint.
---
@rwaldron One down, sixty to go...
=> [[CHORE]] Remove unreachable code

src/jshint.js
A prior commit [1] refactored the token `undefined` to be interpreted as
an identifier rather than a reserved word. This correction made a branch
in the `optionalidentifier` function unreachable, but the branch was
mistakenly persisted. Remove the branch as it cannot influence
JSHint's behavior.
[1] a11d6310c5448304d56be081dc02b4c2a1ff7377
=> [[CHORE]] Remove unreachable branch

src/jshint.js, tests/unit/core.js
Add test for handling of invalid ImportsList (without the branch under
test, no error would be reported when ImportSpecifiers are not
delineated by a comma).
=> [[TEST]] Improve coverage

src/jshint.js, src/scope-manager.js
JSHint's "scopeManager" utility was initially implemented to refer to ECMAScript bindings using the term "label." Because ECMAScript uses the term "label" to describe a completely different language feature, this choice of names was somewhat confusing.
Modify all references to "JSHint labels" to use the more accurate term, "binding." Shorten the term "break label" to simply "label."
=> Improve internal variable names

src/jshint.js
Analyzing a `switch` statement involves tracking the first occurance of
a `case` clause. Only noting its presence is necessary, and it is only
necessary in the context of the token's processing logic.
Replace the Array instance with a boolenan flag scoped to the token's
function.
=> [[CHORE]] Optimize `case` clause tracking

.travis.yml
Use the "build matrix" feature offered by TravisCI in order to simplify
the "script" parameter and to create distinct jobs for the "test-262"
and "test-browser" commands (these were previously run as part of the
job scheduled to run the project's unit tests in Node.js version 10).
=> [[CHORE]] Improve CI configuration

src/jshint.js
The `urls` variable was included in the initial release of JSLint [1]. It was
later removed via [1], before the first public release of JSHint. JSHint has
never used this value.
[1] ca120a731db548c0014320fa0c196edc613536ae
[2] 528bd2e1406eebc44eb6387648d9b63291d3b027
=> [[CHORE]] Remove unused internal variable

src/jshint.js
The name `isLoneArrowParam` implies a value that is `true` when the
identifier in question is a parameter for an arrow function. Update the
value and the subsquent reference to align with this name.
=> [[CHORE]] Align value with variable name

src/jshint.js, tests/unit/options.js, tests/unit/parser.js
@caitp @rwaldron This is the latest in the series of rewrites (the prior patches along these lines were 6759ac9, gh-3419, and gh-3427).
Since the second commit intentionally regresses functionality, we should definitely use a merge commit to land this branch.
Commit messages:
> [[FIX]] Improve parsing of comma operator
>
> Re-implement the improvements reverted by the previous commit. Use
> distinct logic to differentiate this new implementation, including the
> following substantive improvements:
>
> - Parse the expression recursively instead of iteratively. This
>   eliminates the need to duplicate parsing semantics within the grouping
>   operator, and it produces a more predictable syntax tree.
> - Correct the location of the warning emitted for the use of the result
>   of assignment …
=> Re-implement comma parsing improvements

src/jshint.js
@caitp @rwaldron This is the latest in the series of rewrites (the prior patches along these lines were 6759ac9, gh-3419, gh-3427, and gh-3434).
Since the first commit intentionally regresses functionality, we should definitely use a merge commit to land this branch.
Commit messages:
> [[FIX]] Support spaces in /*global ... */
>
> Re-implement the improvements reverted by the previous commit. Use
> distinct logic to differentiate this new implementation, including the
> following substantive improvements:
>
> - Improve local variable name
> - Avoid variable reassignment
> - Remove unnecessary value assignment
> - Defer value calculation until necessary
>
> Update related directive processing logic to match.
> [[CHORE]] Revert "Support spaces in /*global ... */"
>
> JSHint's sanitization …
=> Re-implement directive processing logic

src/cli.js, tests/cli.js
When linting stdin with the `--filename` option set, config overrides
that were relative to the current directory had no effect. This fixes that
issue, but existing workarounds will still work.
Fixes 2536 (Extra comment at the bottom)
This has been live-tested to fixup the issue identified in the test repo at https://github.com/bostrom/jshint-filename-test.
=> [[FIX]] Use relative paths with `--filename` when recieving from stdin

README.md
The terms of the JSON license [1] disqualify JSHint from the distinction
of "open source" software [2].
[1] https://www.gnu.org/licenses/license-list.html#JSON
[2] https://opensource.org/faq#evil
=> [[DOCS]] Correct project description

.gitignore, .travis.yml, docs/cli.md, package.json, tests/website.js
The jshint.com project website generates some content based on the state
of this repository. Changes in this repository could therefore interfere
with the website. This script verifies that when the website is
configured to use the current codebase, it builds successfully and
passes its own test suite.
---
@rwaldron This seems easier for folks to discover and better for the project history (that is: synchronizing changes to the source with changes to the docs). I've taken the initiative to [move the docs from the website](https://github.com/jshint/jshint/commit/2bf827844a7c9f03762001dddf5c7759ff179a54) to this repository and [introduce some automated tests there](https://github.com/jshint/jshint.github.io/commit/3f9dd950a803852387954f76943b2eeae08e35d0). For this last part, I'm suggesting …
=> [[CHORE]] Verify integration with jshint.com

tests/unit/core.js
This functionality was introduced by "Add codes to errors generated by
quit()" [1], but no tests were included. Add a test in order to prevent
regressions.
[1] 537dcbd4be49f5b52ede08e98b23e49bbc5e4bbc
=> [[CHORE]] Add regression test for code from `quit`

tests/cli.js, tests/regression/libs/backbone.js
There is a small typo in tests/cli.js, tests/regression/libs/backbone.js.
Should read `overridden` rather than `overriden`.
=> docs: Fix simple typo, overriden -> overridden

src/messages.js, tests/unit/parser.js
The message "Bad invocation" is overly vague, forcing users to guess
about its intent and its status as a recommendation. Reword the message
to more specifically describe the concern: that the pattern is uncommon.
=> [[DOCS]] Improve message for warning W067

src/scope-manager.js
Expand explanation on the special treatment of the `__proto__` property
and consistently reference the explanation from every location where it
is relevant.
=> [[DOCS]] Consolidate information on workaround

src/jshint.js, tests/unit/fixtures/max-cyclomatic-complexity-per-function.js, tests/unit/options.js
=> [[FIX]] maxcomplexity doesn't take into account `&&`

package.json
Address vulnerability of type "Prototype Pollution in lodash" https://github.com/advisories/GHSA-p6mc-m468-83gw
It is not sure whether this is at all relevant for jshint, but at the moment, GitHub's Dependabot sends vulnerability alerts to all respositories with a dependency to jshint, e.g.
https://github.com/alexandrainst/node-red-contrib-parser-ini/network/alert/package-lock.json/lodash/closed
So it would be nice to issue a new jshint release ASAP to offer an easy way forward for those projects with a (dev) dependency to jshint.
https://github.com/lodash/lodash/wiki/Changelog
=> [[Fix]] Update Lodash to latest 4.17.19

CONTRIBUTING.md
Now that the project has been successfully relicensed, we have no need
to collect signatures from contributors.
---
Coincidentally, [CLAHub recently went down](https://github.com/clahub/clahub/issues/174). (The good news is that I'd already downloaded JSHint's signatures.)
=> [[CHORE]] Remove instructions on CLA

src/jshint.js, tests/unit/fixtures/newcap.js
https://262.ecma-international.org/#sec-regexp-constructor
...
function call RegExp(…) is equivalent
to the object creation expression new RegExp(…)
with the same arguments
...
=> [[Fix]] Don't warn when RegExp() is used without 'new'.

src/jshint.js, tests/unit/fixtures/newcap.js
https://262.ecma-international.org/#sec-function-constructor
...
the function call Function(…) is equivalent to the object creation
expression new Function(…) with the same arguments
...
=> [[FIX]] Don't warn when Function() is used without 'new'.

src/jshint.js, tests/unit/core.js, tests/unit/parser.js
These restrictions are imposed implicitly by precedence in the
ECMAScript grammar rather than any explicit "early error" rule.
---
I'm surprised that the Pratt parser doesn't enforce this kind of restriction automatically. Maybe I'm misunderstanding something though--I'm a bit rusty here. @rwaldron / @caitp: could I get a second opinion?
If this kind of explicit guard *is* necessary, then I suspect we're missing a lot of others.
=> [[FIX]] Enforce restrictions on `new` operand

src/jshint.js, tests/unit/parser.js
Take care to only disable warning W030 for the "function call" form of
the optional chaining feature; the warning is still relevant for
property access.
=> [[FIX]] Allow optional chaining call as satement

src/jshint.js, src/options.js, tests/unit/core.js, tests/unit/parser.js
As mentioned in #3444 , `E043` is triggered with "Too many Errors" even if there are just warnings in the checked code. This happens because the condition to trigger the said `E043` error is:
```
if (JSHINT.errors.length >= state.option.maxerr)
quit("E043", t);
```
Which clearly checks for the total count of all the messages in `JSHINT.errors` array, The issue is that, this array not only contains errors but also warnings and informative messages. This makes the `E043` run even if there are no errors but only warnings exceeding the count defined in `maxerr` config.
This PR will modify the condition for running into `E043`, by ignoring all warnings and other messages and considering only errors.
This also updates the `maxerr` documentation to reflect the above change.
The tests changed to …
=> [[FIX]] Limit "Too many Errors" (E043) to errors only

src/lex.js, tests/unit/core.js
Changes the handling of escape sequence case for `\"` in the **lex.js** file. Earlier, it converted `\"` into `\\\"`, which is not the correct js equivalent for the case as it should be `"` only. This was causing issue #3315 as `\" != "` that is why jshint considers them different strings.
Fixes and Closes #3315
=> [[FIX]] change escape-sequence handler for double quotes (\")

src/jshint.js, tests/unit/parser.js
=> [[FIX]] Tolerate unterminated nullish coalescing

src/vars.js
Hello,
I have no idea why this hasn't been noticed before, but some well-known globals are missing from `vars.js`. Here's what I've added:
- _BigInt_ for ES 11
- _Intl_ for node
- _specify_ and it's counterpart _xspecify_ for mocha
- _URLSearchParams_ for browser and node
This change is really easy to merge and I'm looking forward to seeing it in the next release.
=> Missing well-known globals

README.md
The site is down, from archive.org it seems since October or November: https://web.archive.org/web/*/david-dm.org . The [last snapshot](https://web.archive.org/web/20211002064243/https://david-dm.org/) shows the most announcement was 2016, so it seems the service has not been maintained in a while.
=> [[DOCS]] Remove david-dm badges

src/jshint.js, src/options.js, src/vars.js, tests/unit/core.js
Include `globalThis` in the set of global bindings available in
ES2020-compliant runtimes. Add the instructions necessary to apply this
set. Extend the document of the `esversion` option to mention these
features.
=> [[FIX]] Recognize ES2020 globals

src/jshint.js, tests/unit/parser.js
We used to mark `async function` as unreachable instead of treating it as any other late function definition. This change makes jshint react to `async` keyword in the same way as it reacted to `function` keyword.
=> [[FIX]] Tolerate late definition of async function

src/jshint.js, tests/unit/core.js
Warning W080 is inappropriate for constant bindings because, unlike `var` and `let` declarations, `const` requires an initializer.
Relax the emission of W080 to allow initializing constant bindings with `undefined`. Add unit tests to verify that the warning continues to be emitted for constant bindings declared in ES2015 destructuring patterns.
=> [[FIX]] Allow initializing const bindings to undef

src/messages.js, tests/unit/core.js, tests/unit/options.js
With the exception of `for..of` and `for..in` heads, constant binding declarations which lack an initializer are syntactically invalid. Despite this, the warning emitted for the construction suggests that the problem lies in runtime behavior. In fact, the constant is not initialized to any value because the code is never evaluated.
Rephrase the warning to more accurately describe the issue.
=> [[FIX]] Correct error message

src/cli.js, src/jshint.js
There are small typos in:
- src/cli.js
- src/jshint.js
Fixes:
- Should read `necessarily` rather than `necessarilly`.
- Should read `linting` rather than `liniting`.
- Should read `delimiter` rather than `delimeter`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos
