CONTRIBUTING.md

It's just a proposal, and kinda poorly written. WDYT?

[[DOCS]] Document proposed commit message guidelines

---

tests/cli.js

This improves JSHint's CLI unit tests a bit. Aside from using Nodeunit (via `setUp` and `tearDown` method) and Sinon more effectively (via the "sandbox" feature), it also reduces shared state between test runs. The shared state forced tests to include irrelevant logic, but (more importantly) it could have led to false negatives.
[We first discovered this problem back in October](https://github.com/jshint/jshint/pull/1900#discussion_r18750300), but it's only with [the introduction of code coverage reporting](https://github.com/jshint/jshint/pull/2007) that I felt comfortable doing this refactoring.

Test cleanup

---

src/vars.js

Add new Jasmine 2.1 globals to Jasmine option

---

src/vars.js

Refs:
* https://notifications.spec.whatwg.org/
* https://developer.mozilla.org/en/docs/Web/API/notification

Add Notification to browser globals

---

tests/unit/fixtures/latedef-inline.js
tests/unit/fixtures/shadow-inline.js
tests/unit/options.js

Adds test cases for previously untested portions of defining inline rules. Improves test coverage.

[[TEST]] Test inline rules

---

src/cli.js
tests/cli.js

When jshintrc is incorrect, i want to know what happened.
Therefore i am adding the error message to the error and not just saying that the file couldn't be parsed

informative error when jshintrc is invalid

---

src/jshint.js
tests/unit/parser.js

Previously untested area, improve test coverage and fixed an error reporter.

[[TEST]] Test linting JSON

---

src/jshint.js
src/lex.js
tests/unit/core.js
tests/unit/fixtures/es6-template-literal-tagged.js

[[FEAT]] parse and lint tagged template literals

---

src/vars.js

[[FIX]] predefine HTMLTemplateElement in browser

---

src/jshint.js
src/messages.js
src/options.js
tests/unit/options.js

[[FEAT]] add `varstmt` enforcement option to disallow use of VariableStatements

---

examples/.jshintrc

Based on [the docs](http://jshint.com/docs/options/#unused)

Add missing options for `unused`

---

src/jshint.js
tests/unit/fixtures/unused.js
tests/unit/options.js

[[FIX]] Ignore unused arrow-function parameters if unused: vars

---

src/vars.js

Spec: http://www.w3.org/TR/navigation-timing/#sec-window.performance-attribute

[[FIX]] Add `window.performance` to browser vars

---

src/jshint.js
src/lex.js
src/state.js
tests/unit/parser.js

Triggering a test build to ensure this patch still passes on latest `master` and with my change applied.

Fix ignore

---

src/jshint.js
tests/unit/core.js
tests/unit/options.js

[[FIX]] It is not un-necessary to assign undefined in a loop

---

src/scope-manager.js
tests/unit/core.js

[[FIX]] Don't throw E056 for vars used in two functions

---

src/jshint.js
tests/unit/parser.js

A couple patches to improve the detection and reporting of the "Bad assignment" error. I've included more detail in the commit messages.

Improve E031, "Bad assignment."

---

README.md

[[DOCS]] Add thanks for former maintainers

---

src/messages.js
tests/regression/thirdparty.js
tests/unit/options.js
tests/unit/parser.js

Expand the message to describe the rationale for the warning.

[[DOCS]] Improve warning message for W040

---

src/jshint.js
src/state.js
tests/unit/options.js

This patch contains two refactoring commits followed by a bug fix that should
resolve both gh-2909 and ~~gh-3051~~ gh-2902.

Esversion normalization

---

src/jshint.js
tests/unit/parser.js

[[FIX]] Fail gracefully on invalid `if` syntax

---

src/lex.js
tests/test262/expectations.txt
tests/unit/parser.js

@rwaldron 5 tests down, 1,411 to go :P.
If this looks good to you, please rebase (if necessary) and merge using git's fast-forward strategy.

Correct a few bugs in escape sequence parsing

---

src/jshint.js
src/scope-manager.js
tests/test262/expectations.txt
tests/test262/test.js
tests/unit/core.js
tests/unit/fixtures/latedef-esnext.js
tests/unit/options.js

Hey @rwaldron: if this looks good to you, can you please merge as individual
commits? I want to make sure we stick to the contribution guidelines for commit
messages, but squashing this pull request via the GitHub.com interface will
create a commit that is invalid by those standards.

Import hoisting

---

src/jshint.js
tests/unit/options.js

This extends gh-2797 with a few minor alterations.
@nicolo-ribaudo This review has been a long time coming--I felt obliged to implement my feedback directly. Do these changes look good to you?

[[FIX]] Throw W033 instead of E058 when the ; after a do-while stmt is missing (continued)

---

src/lex.js
tests/unit/options.js
tests/unit/parser.js

In addition, do not emit the E029 error. Maintain the error code itself
to replace with W043 in a future release.
This is intended to resolve gh-3152.

[[FIX]] Correct location reported for W043

---

.mailmap

In this way my past contributions are mapped correctly.

[[CHORE]] Add my new name to .mailmap

---

src/jshint.js
src/scope-manager.js
src/vars.js
tests/test262/expectations.txt
tests/unit/core.js
tests/unit/envs.js
tests/unit/options.js
tests/unit/parser.js

@rwaldron since this updates a few tests, it's going to suffer from conflicts
if gh-3176 is merged first. I'm happy to rebase at that time, but I'm holding
off for now because I don't want to presume that other patch is going to land
at all (since it's a little controversial).

Fixes: inc/dec and bindings

---

src/lex.js
src/reg.js
tests/test262/expectations.txt

@rwaldron I've been working on the `v2.10.0` branch, and it took me quite some time to figure out what was going wrong here (I only recently upgraded my development machine to Node.js version 8.)

[[FIX]] Correct interpretation of whitespace

---

src/jshint.js
src/messages.js
src/scope-manager.js
tests/test262/expectations.txt
tests/unit/parser.js

Hey @rwaldron,
Here are some more improvements in service of gh-2604. Note that I'm targeting `master`--these are all bugs that can be observed in the current release of JSHint. Who would have guessed implementing async functions would uncover so many problems?
I originally wrote these patches across a few distinct branches, but I decided that the work we'd have to do resolving conflict didn't justify the benefit of being able to land them independently. That said, if you'd like to put off some part of this and land the rest, I'm happy to factor it apart as necessary. Let me know!

Miscellaneous fixes

---

.travis.yml
src/jshint.js
src/scope-manager.js

Hey @rwaldon: can you believe we haven't been running lint checks in CI?

Fix linting

---

src/lex.js
src/messages.js
src/reg.js
tests/unit/parser.js

No justification could be found for this warning. See https://github.com/jshint/jshint/issues/2741
This should resolve gh-2741.

[[FIX]] Remove warning W100

---

README.md

Added Spotify to companies who use JSHint

---

src/messages.js

Remove unused warnings

---

src/vars.js

Introduce omitted globals for browser and web workers

---

src/jshint.js
tests/unit/parser.js

This is intended to resolve gh-3358.

[[FIX]] Allow built-in method names in classes

---

src/jshint.js
tests/unit/core.js

This is intended to resolve gh-3367.

[[FIX]] Correct parsing of exported async fns

---

src/jshint.js
tests/unit/options.js
tests/unit/parser.js

This is intended to resolve gh-3395. I had to fix a previously-unreported issue with the `singleGroups` option to get there.

Correct binding power of AwaitExpression

---

src/jshint.js
tests/unit/parser.js

[[FIX]] Do not crash on invalid program code

---

src/jshint.js
tests/unit/parser.js

@rwaldron @caitp Writing something truly distinct was a little tough for this small patch, but the small size fortunately also makes originality less critical. I'm hoping that my discovery and correction of a previously-unreported bug lends some weight to the novelty of the new implementation.

Re-implement "comma fixes"

---

docs/install.md

I added VS Code JSHint extension in `install.md`.

Add vscode jshint

---

docs/cli.md
docs/relicensing-2020.md

Fixes markdown syntax

---

src/jshint.js
src/state.js
tests/unit/options.js

Extend the internal data structure used to track directives so that it
can be used to correctly report location information. Document the type
of this structure in the source file where it is initialized.

[[FIX]] Correct location reported for directive

---

package.json

Resolves: #3546
https://github.com/advisories/GHSA-35jh-r3h4-6jhm

[[CHORE]] CVE-2021-23337 in lodash

---

src/jshint.js
tests/unit/parser.js

[[FIX]] Allow invoking result of optional chaining

---

src/jshint.js
tests/unit/parser.js

[[FIX]] Tolerate dangling NewExpression

---

src/vars.js

Re: https://github.com/jshint/jshint/issues/3567#issuecomment-917540451
See history in https://nodejs.org/api/url.html#url_class_url.

bugfix: add URL for node in src/vars.js

---

package-lock.json

This changeset was generated automatically by the npm utility via the
following command:
$ npm install

[[CHORE]] Update version of package manifest
